#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/0b830fc0a1219b50196c7f202764f8ee3f4d0c48

  - name: oldcontent
    origin: https://lkrapf.helix-demo.xyz
    url: https://asanso.helix-demo.xyz
