#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/1285d8613e6a62420978bc086be3c9f3c31d0bf1

  - name: oldcontent
    origin: http://127.0.0.1
    url: https://asanso.helix-demo.xyz
