#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/121d5d4198154dba75f003ecd745672d5fbdc011

  - name: oldcontent
    origin: https://asanso.github.io/helix-playground
    url: https://asanso.helix-demo.xyz
