#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/d1f184ed663c8d82e1f11651176d76409ca77355

  - name: oldcontent
    origin: https://jsfiddle.net/kxzrb9yw/
    url: https://asanso.helix-demo.xyz
