#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/80af5244967cd658369cf2a29a600552b8d72c83

  - name: oldcontent
    origin: http://localhost:8000
    url: https://asanso.helix-demo.xyz
