#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/c781d7cbcd1aaba487b2b4b108eef1ccb6a9d652

  - name: oldcontent
    origin: https://www.adobe.io
    url: https://lkrapf.helix-demo.xyz
