#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/284ce17281e5c9f5e1b5eae3f197deddef895d8f

  - name: oldcontent
    origin: https://www.adobe.io
    url: https://asanso.helix-demo.xyz
