#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/c3de8250c646f2c97a57dca5483e23e9c6be5e67

  - name: oldcontent
    origin: https://raw.githubusercontent.com/asanso/helix-playground/master/index.html
    url: https://asanso.helix-demo.xyz
