#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/d74dbe00fa1e06030fc527ffcec1abcd6a5146db

  - name: oldcontent
    origin: http://blog.intothesymmetry.com/
    url: https://asanso.helix-demo.xyz
