#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/fecad9c5de69eb34d6324b44f8171354e79d175e

  - name: oldcontent
    origin: https://lkrapf.helix-demo.xyz
    url: https://asanso.helix-demo.xyz
