#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/b03a5fa6681859cea5b7d33d540c71a15ba27d40

  - name: oldcontent
    origin: https://asanso.helix-demo.xyz
    url: https://asanso.helix-demo.xyz
