#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/4fade0635dc16bfdc649451e9ed404fd87fb98ea

  - name: oldcontent
    origin: https://lkrapf.helix-demo.xyz
    url: https://asanso.helix-demo.xyz
