#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/dea049ac49d61264b1f800cbaee2b540aad2ab0d

  - name: oldcontent
    origin: javascript:alert(document.domain)
    url: https://asanso.helix-demo.xyz
