#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/ff2f811b0a96135719ee558b374410719bc18145

  - name: oldcontent
    origin: https://asanso2.github.io
    url: https://asanso.helix-demo.xyz
