#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/9361f14b7c42ca4b46264f9fa1cb8284948b5261

  - name: oldcontent
    origin: https://asanso.helix-demo.xyz
    url: https://asanso.helix-demo.xyz:a@asanso.helix-demo.xyz
