#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/24fa410ca8daf105eaea299ab3f57f1a989a9686

  - name: oldcontent
    origin: https://asanso.github.io/
    url: https://asanso.helix-demo.xyz
