#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/828e1d415f6a77107dbae1e4f1004a633d034ef4

  - name: oldcontent
    url: https://asanso.helix-demo.xyz:a@lkrapf.helix-demo.xyz
    origin: https://asanso.helix-demo.xyz
