#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/94412565b2686f79561638ba5474b69028f7d4c1

  - name: oldcontent
    origin: https://git.corp.adobe.com/
    url: https://asanso.helix-demo.xyz
