#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/808d83f773016cb53be67c5a05d929c283d6a5e7

  - name: oldcontent
    url: https://lkrapf.helix-demo.xyz
    origin: https://asanso.helix-demo.xyz
