#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/18c7de83df7f754dcb8f87e9a2de4f8494666619

  - name: oldcontent
    origin: https://www.adobe.io
    url: https://asanso.helix-demo.xyz
