#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/67472cc6ea46d5003294a4ab30450d62d69e4c28

  - name: oldcontent
    url: https://lkrapf.helix-demo.xyz:a@asanso.helix-demo.xyz
    origin: https://asanso.helix-demo.xyz
