#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/d6d1f3ce5df94f03113b4102a7028a5a9e40f276

  - name: oldcontent
    origin: http://blog.intothesymmetry.com
    url: https://asanso.helix-demo.xyz
