#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/e7377ef7f6496e0fc1039c1ca809fd159f1663ee

  - name: oldcontent
    origin: https://lkrapf.helix-demo.xyz
    url: https://lkrapf.helix-demo.xyz
