#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/asanso/helix-playground.git"

strains:
  - name: default
    code: https://github.com/asanso/helix-playground.git#master
    content: https://github.com/asanso/helix-playground.git#master
    static: https://github.com/asanso/helix-playground.git/htdocs#master
    package: asanso/703f52efbe31bed93f7216f6308f875807ff88d8

  - name: oldcontent
    origin: https://www.intothesymmetry.com
    url: https://asanso.helix-demo.xyz
